from dataclasses import dataclass

from config.state import GraphState
from google import genai
from google.genai import types
from nodes.print_response import PrintResponse
from pydantic_graph import BaseNode, GraphRunContext


@dataclass
class ExecuteAPI(BaseNode[GraphState]):
    """Executes the content generation API request.

    This class is responsible for sending a request to the Gemini API with
    the configured prompt and generation settings. It supports both document-
    based and prompt-based content generation by incorporating appropriate
    content parts from the `GraphState`.

    The response generated by the API is stored in the state and forwarded to
    the next node for further processing.

    Note:
        This class does not store attributes directly. It relies on the
        `GraphState` provided in the `ctx.state` to access necessary parameters
        such as the API client, model, prompt, and configuration.
    """

    async def run(self, ctx: GraphRunContext[GraphState]) -> PrintResponse:
        """Executes the API request to generate content.

        This method constructs the content request using either a document URL
        or a prompt (or both) and sends it to the Gemini API. The response is
        then stored in the `GraphState` and passed to the next node for display.

        Args:
            ctx (GraphRunContext[GraphState]): The execution context containing
                the shared state, including the API client, model name, prompt,
                document URL, MIME type, and generation settings.

        Returns:
            PrintResponse: The next node in the execution sequence, responsible
                for printing the API response.
        """
        contents = []

        # Add document from URL if provided
        if ctx.state.document_url:
            contents.append(
                types.Part.from_uri(
                    file_uri=ctx.state.document_url,
                    mime_type=ctx.state.document_mime_type,
                )
            )

        # Add prompt text if provided
        if ctx.state.prompt:
            contents.append(types.Part.from_text(text=ctx.state.prompt))

        # Generate content using the provided Gemini client and configuration
        response = ctx.state.client.models.generate_content(
            model=ctx.state.model,
            contents=contents,
            config=ctx.state.config,
        )

        # Store the generated response in the state
        ctx.state.response_text = response.text

        return PrintResponse()
