from dataclasses import dataclass

from config.state import GraphState
from pydantic_graph import BaseNode, End, GraphRunContext


@dataclass
class PrintResponse(BaseNode[GraphState]):
    """Print the response from the Gemini API.

    This class takes the response text stored in the `GraphState` and
    prints it to the console. It is the final step in the graph, which
    outputs the content generated by the Gemini API.

    Attributes:
        None directly, as the response text is retrieved from the state
        object in the `run` method.
    """

    async def run(self, ctx: GraphRunContext[GraphState]) -> End[str]:
        """Print the response text to the console.

        This method prints the response text stored in the `GraphState`
        to the console and returns it as the end result of the graph execution.

        Args:
            ctx (GraphRunContext[GraphState]): The context containing the
                shared state, which includes the response text.

        Returns:
            End[str]: The end node that contains the response text as
                the final output of the graph.
        """
        # Print the generated response text to the console
        print(f"Gemini Response: {ctx.state.response_text}")

        # Return the response text as the final output
        return End(ctx.state.response_text)
