from dataclasses import dataclass

from pydantic_graph import BaseNode, End, GraphRunContext


@dataclass
class PrintResponse(BaseNode[None, None, str]):
    """Print the response from the Gemini API.

    This class takes the response text generated by the Gemini API and
    prints it to the console.

    Attributes:
        response (str): The response text to print.
    """

    response: str

    async def run(self, ctx: GraphRunContext) -> End[str]:
        """Print the response text to the console.

        Prints the response from the Gemini API and ends the process.

        Args:
            ctx (GraphRunContext): The context in which the graph is running.

        Returns:
            End[str]: The end node with the response text.
        """
        print(f"Gemini Response: {self.response}")
        return End(self.response)
