import base64

from google import genai
from google.genai import types


def generate():
    """Generates a response from the Gemini AI model using a PDF input.

    This function reads a PDF file, encodes it in base64, and sends it as an
    input to the Gemini AI model via Google's GenAI API. The AI is asked to
    extract a list of officers from the document, formatted as a JSON object.

    The function configures the model's response parameters, including safety
    settings and output format. It streams the model's response and accumulates
    the result into a text variable, which is printed and returned.

    Returns:
        str: The full response generated by the AI model.
    """
    client = genai.Client(
        vertexai=True,
        location="us-central1",
    )

    with open("10k.pdf", "rb") as file:
        pdf_data = file.read()
        encoded_pdf = base64.b64encode(pdf_data).decode("utf-8")

    document1 = types.Part.from_bytes(
        data=encoded_pdf,
        mime_type="application/pdf",
    )

    model = "gemini-2.0-flash-001"
    contents = [
        types.Content(
            role="user",
            parts=[
                document1,
                types.Part.from_text(
                    text="""Give me a list of the Officers [{name:name, age:age, 
                    title:title}] use empty string '' on values with no data"""
                ),
            ],
        )
    ]

    generate_content_config = types.GenerateContentConfig(
        temperature=1,
        top_p=0.95,
        max_output_tokens=8192,
        response_modalities=["TEXT"],
        safety_settings=[
            types.SafetySetting(category="HARM_CATEGORY_HATE_SPEECH", threshold="OFF"),
            types.SafetySetting(
                category="HARM_CATEGORY_DANGEROUS_CONTENT", threshold="OFF"
            ),
            types.SafetySetting(
                category="HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold="OFF"
            ),
            types.SafetySetting(category="HARM_CATEGORY_HARASSMENT", threshold="OFF"),
        ],
        response_mime_type="application/json",
        response_schema={
            "type": "OBJECT",
            "properties": {"response": {"type": "STRING"}},
        },
    )

    # Accumulate the streaming chunks into a variable.
    response_text = ""
    for chunk in client.models.generate_content_stream(
        model=model,
        contents=contents,
        config=generate_content_config,
    ):
        response_text += chunk.text

    # Now you have the full response stored in response_text.
    print("Full Response:")
    print(response_text)
    print(type(response_text))
    # You can also return it for further processing.
    return response_text


# Store the response in a variable.
stored_response = generate()
